# Generated by Django 4.2 on 2023-05-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0003_alter_feedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='Имя', max_length=40),
        ),
    ]
